select * from GiaoDichThanhToan
select * from HoaDonHocPhi
select * from DangKyKhoaHoc
select * from KhoaHoc
select * from LichDay
select * from LichHocVien
select * from GiangVien_KhoaHoc
select * from PhongBan
select * from PhongHoc
select * from DiemSo
select * from NguoiDung
select * from NguoiDung_VaiTro
select * from VaiTro
select * from ThongTinGiangVien