//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyKhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DangKyKhoaHoc()
        {
            this.DiemSoes = new HashSet<DiemSo>();
            this.HoaDonHocPhis = new HashSet<HoaDonHocPhi>();
            this.LichHocViens = new HashSet<LichHocVien>();
        }
    
        public int MaDangKy { get; set; }
        public int MaHocVien { get; set; }
        public int MaKhoaHoc { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public int HocPhiThoiDiem { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemSo> DiemSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonHocPhi> HoaDonHocPhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHocVien> LichHocViens { get; set; }
    }
}
