//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiemSo()
        {
            this.YeuCauSuaDiems = new HashSet<YeuCauSuaDiem>();
        }
    
        public int MaDiem { get; set; }
        public int MaDangKy { get; set; }
        public int MaGiangVien { get; set; }
        public string LoaiKiemTra { get; set; }
        public Nullable<decimal> Diem { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string NhanXet { get; set; }
    
        public virtual DangKyKhoaHoc DangKyKhoaHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauSuaDiem> YeuCauSuaDiems { get; set; }
    }
}
