//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichThanhToan
    {
        public int MaGiaoDich { get; set; }
        public int MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public int SoTien { get; set; }
        public string PhuongThuc { get; set; }
        public string MaChungTu { get; set; }
        public string GhiChu { get; set; }
        public int NguoiXacNhan { get; set; }
    
        public virtual HoaDonHocPhi HoaDonHocPhi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
