//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonHocPhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonHocPhi()
        {
            this.GiaoDichThanhToans = new HashSet<GiaoDichThanhToan>();
        }
    
        public int MaHoaDon { get; set; }
        public int MaDangKy { get; set; }
        public int TongTien { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DangKyKhoaHoc DangKyKhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichThanhToan> GiaoDichThanhToans { get; set; }
    }
}
