//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHocVien
    {
        public int MaLichHocVien { get; set; }
        public int MaDangKy { get; set; }
        public int MaLich { get; set; }
        public string DiemDanh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DangKyKhoaHoc DangKyKhoaHoc { get; set; }
        public virtual LichDay LichDay { get; set; }
    }
}
