//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichDay()
        {
            this.LichHocViens = new HashSet<LichHocVien>();
        }
    
        public int MaLich { get; set; }
        public int MaKhoaHoc { get; set; }
        public int MaGiangVien { get; set; }
        public int MaPhong { get; set; }
        public System.DateTime NgayDay { get; set; }
        public System.TimeSpan GioBatDau { get; set; }
        public System.TimeSpan GioKetThuc { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHocVien> LichHocViens { get; set; }
    }
}
