//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuHeThong
    {
        public int MaLichSu { get; set; }
        public string TenBang { get; set; }
        public string HanhDong { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
    }
}
