//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeThongQuanLyTrungTamNgoaiNguEntities1 : DbContext
    {
        public HeThongQuanLyTrungTamNgoaiNguEntities1()
            : base("name=HeThongQuanLyTrungTamNgoaiNguEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DangKyKhoaHoc> DangKyKhoaHocs { get; set; }
        public virtual DbSet<DiemSo> DiemSoes { get; set; }
        public virtual DbSet<GiaoDichThanhToan> GiaoDichThanhToans { get; set; }
        public virtual DbSet<HoaDonHocPhi> HoaDonHocPhis { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<LichDay> LichDays { get; set; }
        public virtual DbSet<LichHocVien> LichHocViens { get; set; }
        public virtual DbSet<LichSuHeThong> LichSuHeThongs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<PhongHoc> PhongHocs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinGiangVien> ThongTinGiangViens { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
        public virtual DbSet<YeuCauSuaDiem> YeuCauSuaDiems { get; set; }
    }
}
