//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiangVien
    {
        public int MaNguoiDung { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
        public string ChuyenMon { get; set; }
        public string BangCap { get; set; }
        public Nullable<int> LuongCoBan { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
