//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauSuaDiem
    {
        public int MaYeuCau { get; set; }
        public int MaDiem { get; set; }
        public int MaGiangVien { get; set; }
        public Nullable<decimal> DiemCu { get; set; }
        public Nullable<decimal> DiemMoi { get; set; }
        public string NhanXetMoi { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public Nullable<int> MaAdminDuyet { get; set; }
        public string GhiChuAdmin { get; set; }
    
        public virtual DiemSo DiemSo { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
